### ISSUE TITLE
D Isuueコメントの例

### ISSUE THREAD

**Issue by kkudou23** [H-tashiro08/gitremote#5]
### 問題の内容
複数の問題をひとつのIssueに含めない。面倒だけど問題の数だけIssueを発行する。

### 実行環境
OSやブラウザのバージョンなど

> Windows 10、Chrome 44

### 再現手順
できる限り詳しく再現の手順を書く。

> 1. xx画面を表示する
> 2. xx項目にユーザ名を入力する
> 3. xxボタンを押下すると「～～～」というエラーが表示される

### 修正すべき内容
どうなるのが正しい動作を書く。
わかれば修正の仕方も書く。

**Comment by Nayuta9382** [comment]
## システムログインの実装
1.ログイン画面に遷移
2.ログインフォームに入力
3.ログインボタンクリック
4.エラーが出た場合に対応する

## 目的
例. ログインできるようにする

## タスク
   細かいタスクがある場合は書き出す
- [ ] ユーザー,パスワード入力欄
- [ ] ボタン押下による認証機能の実装
- [ ] 入力エラーへの対応
